@Server=localhost:4004
@Entity=Customers
@id=20193604-6bde-4eea-af89-951abe3b6808

###
GET http://{{Server}}/odata/v4/main/{{Entity}}
Content-Type: application/json

###
GET http://{{Server}}/odata/v4/main/{{Entity}}(ID={{id}})
Content-Type: application/json

###
# Selecionando campos específicos com #select e filtrando valores com $filter
GET http://{{Server}}/odata/v4/main/{{Entity}}?$select=ID,firstName,lastName,email&$filter=firstName eq 'Rodrigo'

###
POST http://{{Server}}/odata/v4/main/{{Entity}}
Content-Type: application/json

{
    "ID": "{{id}}",
    "firstName": "Rodrigo",
    "lastName": "Araujo",
    "email": "rodrigo.araujo@email.com"
}

###
PATCH  http://{{Server}}/odata/v4/main/{{Entity}}(ID={{id}})
Content-Type: application/json

{
    "email": "araujo.rodrigo@email.com"
}

###
DELETE http://{{Server}}/odata/v4/main/{{Entity}}(ID={{id}})
Content-Length: 0

###
# Descobrindo a quantidade de registros com $count
GET http://{{Server}}/odata/v4/main/{{Entity}}/$count

### 
# Paginação com $skip e $top
GET http://{{Server}}/odata/v4/main/{{Entity}}?$skip=10&$top=5