@Server=localhost:4004
@Entity=SalesOrderHeaders
@ProductID=19725797-e863-4377-beca-a756e6863896
@PrdouctStockZero=18985828-1a5f-4472-9b32-a41fe1ff76b6
@CustomerID=20193604-6bde-4eea-af89-951abe3b6808
@id=4d9ab65c-7c09-428b-bf29-703db8eea52f

GET http://{{Server}}/odata/v4/main/{{Entity}}
Content-Type: application/json
    
###

POST http://{{Server}}/odata/v4/main/{{Entity}}
Content-Type: application/json

{
    "ID": "{{id}}",
    "customer_ID": "{{CustomerID}}",
    "items": [
        {
            "product_ID": "{{ProductID}}",
            "quantity": 10,
            "price": 5000
        },
        {
            "product_ID": "{{ProductID}}",
            "quantity": 5,
            "price": 5000
        }
    ],
    "totalAmount": 5000
}

###

PATCH http://{{Server}}/odata/v4/main/{{Entity}}(ID=5336100b-bb59-4b32-8331-69179f5b74e5)
Content-Type: application/json

{
    "ID": "12345"
}
###

DELETE http://{{Server}}/odata/v4/main/{{Entity}}(ID=5336100b-bb59-4b32-8331-69179f5b74e5)
Content-Length: 0

###
# Acessando entidade filha com $expand
GET http://{{Server}}/odata/v4/main/{{Entity}}(ID={{id}})?$expand=items