@Server=localhost:4004
@Entity=SalesOrderHeaders
@ProductID=800fafc9-c69b-4134-b4c9-1f3ceb104a8b
@CustomerID=196aaff8-af74-465e-8f9b-9c03eb4317a9
@id=4d9ab65c-7c09-428b-bf29-703db8eea52f

GET http://{{Server}}/odata/v4/main/{{Entity}}
Content-Type: application/json
    
###

POST http://{{Server}}/odata/v4/main/{{Entity}}
Content-Type: application/json

{
    "ID": "{{id}}",
    "customer_ID": "{{CustomerID}}",
    "items": [
        {
            "product_ID": "{{ProductID}}",
            "quantity": 10,
            "price": 5000
        }
    ],
    "totalAmount": 5000
}

###

PATCH http://{{Server}}/odata/v4/main/{{Entity}}(ID=5336100b-bb59-4b32-8331-69179f5b74e5)
Content-Type: application/json

{
    "ID": "12345"
}
###

DELETE http://{{Server}}/odata/v4/main/{{Entity}}(ID=5336100b-bb59-4b32-8331-69179f5b74e5)
Content-Length: 0

###
# Acessando entidade filha com $expand
GET http://{{Server}}/odata/v4/main/{{Entity}}(ID={{id}})?$expand=items